name:                scrapbox
version:             0.1.0.0
github:              "HirotoShioi/scrapbox"
license:             BSD3
author:              "Hiroto Shioi"
maintainer:          "shioihigg@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/HirotoShioi/scrapbox#readme>

dependencies:
- attoparsec
- base >= 4.7 && < 5
- bytestring
- cmark
- hspec
- mtl
- network-uri
- parsec
- QuickCheck
- rio
- say
- split
- text

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -Wnoncanonical-monad-instances

default-extensions:
- NoImplicitPrelude

library:
  source-dirs: src
  exposed-modules: Scrapbox
                   Scrapbox.Types
                   Scrapbox.Internal
  other-modules: Examples.Example1
                 Examples.Example2
                 Scrapbox.CommonMark.Lib
                 Scrapbox.CommonMark.TableParser
                 Scrapbox.Constructors
                 Scrapbox.DiffFinder
                 Scrapbox.Parser.Item
                 Scrapbox.Parser.Scrapbox
                 Scrapbox.Parser.ScrapText
                 Scrapbox.Parser.Utils
                 Scrapbox.Render
                 Scrapbox.Utils

tests:
  scrapbox-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - scrapbox
